# Generated by Django 3.0.7 on 2020-06-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('DEBUG', 'DEBUG')], max_length=16)),
                ('archived', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('address', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
