# Generated by Django 3.0.7 on 2020-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0002_error_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='category',
            field=models.CharField(choices=[('PRODUÇÃO', 'PRODUÇÃO'), ('HOMOLOGAÇÃO', 'HOMOLOGAÇÃO'), ('DEV', 'DEV')], default='DEV', max_length=16),
            preserve_default=False,
        ),
    ]
