# Generated by Django 3.0.7 on 2020-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0003_error_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='title',
            field=models.TextField(default='Titulo Atrasado', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='error',
            name='category',
            field=models.CharField(choices=[('PRODUÇÃO', 'Produção'), ('HOMOLOGAÇÃO', 'Homologação'), ('DEV', 'Dev')], max_length=16),
        ),
        migrations.AlterField(
            model_name='error',
            name='level',
            field=models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('DEBUG', 'Debug')], max_length=16),
        ),
    ]
