# Generated by Django 3.0.7 on 2020-06-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0004_auto_20200623_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
