# Generated by Django 3.0.7 on 2020-07-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0005_auto_20200630_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='events',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='error',
            name='address',
            field=models.GenericIPAddressField(default='127.0.0.1', protocol='IPv4'),
            preserve_default=False,
        ),
    ]
