# Generated by Django 3.0.8 on 2020-07-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0006_auto_20200706_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='address',
            field=models.GenericIPAddressField(),
        ),
    ]
