# Generated by Django 3.0.7 on 2020-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='token', max_length=42),
            preserve_default=False,
        ),
    ]
